### ISSUE TITLE
doesn't work with clearly preprocessed pages

### ISSUE THREAD

**Issue by kasyaar** [schomery/dictionary#1]
Hi
I'm using firefox 39.0.3 with Clearly plugin 10.2.1.7.1 and Dictionary Everywhere 0.1.1
And in Clearly processed pages Dictionary's popup doesn't appear when I select a word

**Comment by schomery** [comment]
Thanks! Can you confirm the fix on https://github.com/schomery/dictionary/blob/master/src.safariextension/executables/extension.xpi?raw=true

Download the XPI and drop it into your Firefox

**Comment by kasyaar** [comment]
Yup! It works now. Thanks!

**Comment by kasyaar** [comment]
Hi
I just check it on the same configuration in [Firefox Reader View](https://support.mozilla.org/en-US/kb/firefox-reader-view-clutter-free-web-pages)(it's embedded feature in compare to clearly) - same problem.

**Comment by schomery** [comment]
I wish you had reported this a bit sooner. It is now fixed on the dev version:
https://github.com/schomery/dictionary/blob/master/src.safariextension/executables/extension.xpi?raw=true
