### ISSUE TITLE
[Request] Translate using context menu entry instead of floating bubble

### ISSUE THREAD

**Issue by FatOrangutan** [schomery/dictionary#11]
Please consider providing an option to show an entry to translate the selected text in the right click menu instead of using the translation bubble for the same.

**Comment by B00ze64** [comment]
+1 The bubble is cute, but I would prefer an entry in the page context menu, preferably an entry that does not repeat the highlighted text, i.e. "Translate Selection" instead of "Translate 'blablabla...' with Dictionary Anywhere" which quickly becomes too wide and fucks-up the context menu. Best place for the context entry is right after the SEARCH IN menu item (id="context-searchselect").

**Comment by sumyungguy** [comment]
I'd also like to request an alternative to the bubble. 99% of the time I'm selecting text to copy it somewhere, so I don't need to see the bubble. And I'd rather not have event listeners injected into the page, which might conflict with something already there. So I'd like the option to turn the bubble off.

Even better than a context menu for me would be to have a bit of javascript that I could use with the Dorando Keyconfig addon, to trigger the translate panel with the selected text. Thanks!

**Comment by oldman777** [comment]
I completely agree.  An entry to translate the selected text in the right click menu is very useful feature.

**Comment by oldman777** [comment]
I completely agree. An entry to translate the selected text in the right click menu is very useful feature.

When I try to translate the entire page, I see - "The page you have attempted to translate is already in Russian."
When I try to translate the selected text, the translation button does not appear at all on this page.
https://addons.mozilla.org/ru/firefox/addon/dictionary-anywhere/?src=userprofile

**Comment by mooms06** [comment]
+1

**Comment by schomery** [comment]
We will have a new option to translate from the context-menu (as an alternative to the bubble mode) on the upcoming release.

> When I try to translate the selected text, the translation button does not appear at all on this page.

Store pages are protected and there is no way to insert script into them.

**Comment by B00ze64** [comment]
Thank you.
