### ISSUE TITLE
Causes 100% CPU usage on some pages

### ISSUE THREAD

**Issue by sumyungguy** [schomery/dictionary#16]
Steps to reproduce:
1. Create a clean profile and install the addon.
2. Go to for example: https://www.ebay.com/sch/Art-Posters/28009/ or do a search in an Ebay category without a search term.
3. Wait a few seconds, note that CPU usage is less than 2%
4. Click anywhere in a blank area of the page.

Expected results:
Nothing happens.

Actual results:
CPU usage goes to 100% in one core. This problem is not present when the addon is not installed.

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:54.0) Gecko/20100101 Firefox/54.0

**Comment by schomery** [comment]
Thanks for the report. There is a function in this page that causes an infinite loop. I found a method to prevent this (version 0.3.1), but probably this page is going to conflict with other add-ons that use in-page message passing.

**Comment by canufarm** [comment]
Seems that this has something to do with this issue:
https://github.com/schomery/dictionary/issues/17
