### ISSUE TITLE
adds a code in your wysiwyg editor

### ISSUE THREAD

**Issue by kimlop** [schomery/dictionary#22]
Adds a code into the page without your knowledge when you editing a page in Wordpress / Joomla / Drupal.

example code: 
`<div class="itanywhere-activator" style="left: 330px; top: 62px; display: none;" title="Google Translator Anywhere">&nbsp;</div>`

**Comment by mooms06** [comment]
Indeed, I encountered it on ASUS forums: [Weird issue on ASUS forums](https://github.com/schomery/dictionary/issues/24)

**Comment by schomery** [comment]
I need a sample page that I can reproduce this. A website that allows me to register.

**Comment by kimlop** [comment]
Go here https://sdk.ckeditor.com/samples/classic.html
try to translate something on the editor, after click on "Source" and on the bottom of the code you can find the html placed by the extension

**Comment by schomery** [comment]
Please give the dev version a try and confirm it is fixed;

Download https://github.com/schomery/dictionary/archive/master.zip and extract it into a local directory. Disable the original add-on and load the temporary one. You need to point about:debugging -> "Load Temporary add-on" to the WebExtension/manifest.json file.

You are on Firefox, right?

**Comment by kimlop** [comment]
I tried it in two form, it seems ok
thanks
