### ISSUE TITLE
[feature request] show button only on right-click

### ISSUE THREAD

**Issue by myspaghetti** [schomery/dictionary#23]
The translate button appears every time text is selected, which is distracting. It's better if it would appear only when the selection is right-clicked.

**Comment by pr3mar** [comment]
It would be really nice if you could set a [configurable] hotkey for accessing the API, unlike it is right now.

**Comment by whiskytroll** [comment]
If this is implemented I hope it will be as an option (even if it would be a very short options dialogue with only one setting). In my opinion this way of interaction is what sets  PVfGT apart from the rest of the Google translate extensions, and it's a faster way.

**Comment by schomery** [comment]
We will have a new option in the upcoming release to have this right-click alternative.
