### ISSUE TITLE
Firefox Reader View

### ISSUE THREAD

**Issue by rahilwazir** [schomery/dictionary#28]
I was struggling to find any gtranslate plugin after thorough research I found this plugin at last. Most of the time I need google translate in article and I read articles in Firefox builtin Reader view. And this plugin is simply not working on it. Can you please verify is it bug or configuration issue on my end?

**Comment by schomery** [comment]
WebExtension cannot access local pages like the reader view pages. Unfortunetly this is a limitation of WebExtension APIs and there is no workaround for it.
