### ISSUE TITLE
Translator scaling problem

### ISSUE THREAD

**Issue by happysurf** [schomery/dictionary#30]
The translator scaling bubble like 0.75 change the scale also of the web site.
This is annoying.
Last version + Firefox 57beta9 + Windows 10.

**Comment by periannath** [comment]
I'm having the same problem.
This plugin injects `data/panel/inject.js` to translate.google.com site and
it's scale function changes scale of google translate web page, too.

**Comment by schomery** [comment]
Thanks for the report. It is fixed now
