### ISSUE TITLE
Translate selected text through context menu causes endless loop if text was selected by double clicking

### ISSUE THREAD

**Issue by omicron81** [schomery/dictionary#31]
The new feature #11 does not work correctly if text was selected by double-clicking on a word. 

Firefox 56.0
Addon 3.5.0

Reproduction:
1. Open e.g. https://fr.wikipedia.org
2. Select a word by double-clicking on it
3. Open the context menu and choose "Translate Selection"
4. The Google Translator popup opens, but begins to flicker repeatedly. The add-on seems to make multiple requests in the background.

Sometimes this happens only when done a second time. Sometimes the Translator box doesn't open at all.

I could not reproduce it when text was selected without double-clicking.

**Comment by omicron81** [comment]
Addition: The main cause seems to be whitespace characters at the beginning or end of the selection. When selecting a word by double-clicking, usually a whitespace after the word gets selected, too. 
If I select text by dragging the mouse or by using the keyboard and if I consciously include whitespace characters, I can also reproduce the bug.

**Comment by schomery** [comment]
Can you try the latest dev version and confirm the fix?

1. First uninstall the current version
2. Download https://github.com/schomery/dictionary/archive/master.zip
3. Open about:debugging in a browser tab and point "Install Temporary add-on" to WebExtension/manifest.json

**Comment by omicron81** [comment]
Thanks! I can confirm that the latest version fixes the issue.
