### ISSUE TITLE
Save translation to Google Translate's Phrasebook?

### ISSUE THREAD

**Issue by ervasive** [schomery/dictionary#32]
Hi. I'm not sure if it's a bug or intended behaviour, but it would be pretty helpful if the extension could allow us to add translation to Phrasebook directly through floating panel (star icon on image below).

![image](https://user-images.githubusercontent.com/85254/32836857-eb09b8ae-ca13-11e7-8e33-a3e695b13979.png)

Currently it does nothing on click.

Firefox 57.0

Thank you for great extension.

**Comment by u7m** [comment]
Yes that would be a pretty handy feature

**Comment by froxplus** [comment]
this feature is very handy.

**Comment by schomery** [comment]
I am not able to reproduce this anymore. Please try the new release and reopen if you are still experiencing it.
