### ISSUE TITLE
Context menu item in reading mode

### ISSUE THREAD

**Issue by mtunad** [schomery/dictionary#33]
I can't find `translate selection`" in the context menu when I read something in reading mode.

**Comment by oldman777** [comment]
The same issue.  I can't find "**translate selection**" in the context menu.

![2017-11-17_124233_cr](https://user-images.githubusercontent.com/28647829/32941395-bf75b2c2-cb96-11e7-8b84-9f2d2794a493.jpg)

**Comment by ooofest** [comment]
I have noticed that if you disable the "Display word selection bubble" option, then the right-click menu option appears.

However, since these options are selectable via checkboxes and not radio buttons, you'd think that they were not intended to be mutually exclusive.

**Comment by mtunad** [comment]
I already disabled word selection bubble in order to get context menu entry. And it's working fine in normal browsing mode. However, when I right-click in Firefox's Reading Mode feature, I can't find that menu item.

**Comment by schomery** [comment]
@entriol no extension can inject nor interact with the reader view.

**Comment by schomery** [comment]
> However, since these options are selectable via checkboxes and not radio buttons, you'd think that they were not intended to be mutually exclusive.

Thanks for the report. Here is the new look:
![screen shot 2017-11-19 at 10 34 34 am](https://user-images.githubusercontent.com/11704051/32988252-6d17443e-cd15-11e7-83fd-19bbe4588db1.png)

**Comment by mtunad** [comment]
@schomery Are you sure? Because I have extensions that can interact in reader mode
![Here's screenshot of it](https://cdn.pbrd.co/images/GVt6baV.png)
