### ISSUE TITLE
Add-on does not find text to translate on a Firefox Add-on comments page

### ISSUE THREAD

**Issue by ooofest** [schomery/dictionary#34]
Hi, thank you for this work, as it seems a worthy replacement for gTranslate from pre-v57 Firefox days and I like the bubble UI.

I happened to notice that this add-on does not appear to recognize selected text to translate on this page:
https://addons.mozilla.org/en-US/firefox/addon/quick-dial/reviews/

For example,  I tried selecting portions of non-English text from these comments on that page:

**Спасибо за это дополнение!)) Раньше с удовольствием пользовалась Fast Dial, была от приложения в полнейшем восторге! В этом приложении, к сожалению, отсутствует возможность настройки для всех окон "открывать в новой вкладке" - неудобно каждый раз входить в меню. так же не нашла функцию "обновить все закладки". И вообще, настройки в Fast Dial были гораздо понятнее и удобнее. Возможность сделать фон конечно приятна, но гораздо важнее иметь возможность легко и быстро менять закладки местами, открывать все в новой вкладке и обновлять все автоматически.**

**En remplacement de Speedial qui n'est plus supporté, fait la même chose, j'ai réussi a refaire mon écran d'accueil avec mes icônes.
J'aimerais juste pouvoir choisir la hauteur des tuiles.**

But, the bubble didn't appear and when I enabled the right-click menu selection, selecting that option to translate the text resulted in no visible action.

Interestingly, if I try the same action in this github page for the same text as pasted above, this add-on works as expected.

**Comment by schomery** [comment]
All WebExension add-ons cannot inject or interact with web-stores. In Firefox, addons.mozilla.org is the web-store. Try in another domain to test the extension.

**Comment by ooofest** [comment]
Thanks, I didn't realize that limitation existed.  Boy, I am not thrilled with WebExtension limitations.

As per the test I mentioned within this page of the same text, the add-on works on other pages - so, I guess this is worked as designed!

Thanks for your helpful reply - I wonder if it might be useful to mention this inherent limitation in its Firefox Add-Ons page?

**Comment by ooofest** [comment]
Thanks, I didn't realize that limitation existed.  It's great to see what can be done with this add-on thus far, but I am not thrilled with Firefox's WebExtension limitations, to say the least.

As per the test I mentioned within this page using the same text from the "store," the add-on works on other pages - so, I guess this is worked as designed!

Thanks for your helpful reply - I wonder if it might be useful to mention this inherent limitation in its Firefox Add-Ons page?

Closing this item.
