### ISSUE TITLE
ISSUE: definitions do not show up if word is translated twice or more in a row

### ISSUE THREAD

**Issue by d0mf1g** [schomery/dictionary#37]
Example: translate a word using this extension and it will show the translation panel and the definitions panel. If you close the panel and then try to translate the same word again, only the translation panel will show up. The definition panel disappears.

If you click on a different word, the definitions panel will show up. 

If you click on a different word and then back to the original word, the definitions panel will show up. So this issue seems to be only occurring if the same word is translated right after.

**Comment by ghost** [comment]
Yep, I have this issue too

**Comment by schomery** [comment]
I am not able to reproduce this on the new release anymore. Please reopen if you are still experiencing this issue.
