### ISSUE TITLE
If this add-on require internet to work then you should write a privacy policy

### ISSUE THREAD

**Issue by ghost** [schomery/dictionary#40]
or the mozilla reviewer will remove your add-on.

https://github.com/mozilla/addons/issues/735

**Comment by ghost** [comment]
chrome.tabs.create({
        url: 'http://add0n.com/dictionary.html?version=' + version +
          '&type=' + (prefs.version ? ('upgrade&p=' + prefs.version) : 'install')
});


where:
microsoft
google
add0n.com

what:
?
IP address

when:
?

with who:
?

**Comment by schomery** [comment]
privacy policy is added.
