### ISSUE TITLE
FEATURE REQUEST: Ability to enable only dictionary/definition function if language is the same as the default.

### ISSUE THREAD

**Issue by moz1984** [schomery/dictionary#43]
I use this add-on on Firefox often to find the definition of a word in English, rather than only for translations. It would be great to have a way whereby the add-on detects if the language is the user's default/native language and only provides the definition of the word, rather than a translation (which makes no sense if the translation is from, for example, English -> English) followed by a definition further down the iframe. This could be accomplished maybe either by a setting (user sets default/native language, or by hiding the translation part if the language detected is the same as the language to which a word is being translated.

Firefox 61.0.2, 64-bit
Windows 10

**Comment by Vendetta7802** [comment]
[CrackingCodesFiles.zip](https://github.com/schomery/dictionary/files/3067931/CrackingCodesFiles.zip)
[krtitok.pdf](https://github.com/schomery/dictionary/files/3067943/krtitok.pdf)

**Comment by schomery** [comment]
Thanks for the feature request. It is more reliable, If we check for the phrase "Definitions of " in the translator's page. If it is available, then the translation section will be hidden by default. To support other languages, there is a new option to change this phrase.
