### ISSUE TITLE
Not saving language definition. Word not show up in insert box. Tested in Firefox and Chrome

### ISSUE THREAD

**Issue by fernandosicos** [schomery/dictionary#44]
Not saving language definition. Word not show up in insert box. Tested in Firefox Quantum (63.0 (64-bit)) and Chrome (Versão 70.0.3538.77 (Versão oficial) 64 bits).

1 - Select word
2 - Click in popup
3 - Word appear in language target (definition in English, not in Portuguese for example).
4 - If I switch in arrows 2 times, then the translation appears.

It was working previously.

![image](https://user-images.githubusercontent.com/793988/48076970-7ad31800-e1cd-11e8-958e-c37e57bade25.png)

In this case, I selected English (or Auto-detect) to Portuguese. But everytime open english - detected to english.

**Comment by schomery** [comment]
Should have been fixed by now. If not please reopen
