### ISSUE TITLE
Broken Github's project layout

### ISSUE THREAD

**Issue by edouard-lopez** [schomery/dictionary#5]
Nice addon, I love the pop-in.
Unfortunately, using Firefox `45.0b1` github project/issues' pages are broken when enabling your addon. See screenshot below:

![screen shot 2016-02-04 at 11 21 55](https://cloud.githubusercontent.com/assets/1212392/12812307/e5984512-cb31-11e5-8389-b646a47042c0.png)

Simply disabling addon make pages works.
### Error

> Content Security Policy: The page's settings blocked the loading of a resource at self ("default-src *").

**Comment by schomery** [comment]
Is this fixed on the latest release?
https://addons.mozilla.org/en-US/firefox/addon/dictionary-anywhere/versions/

**Comment by edouard-lopez** [comment]
It's fixed, thanks !
