### ISSUE TITLE
[Request] Please provide option to Translate page without opening New Tab.

### ISSUE THREAD

**Issue by gaveitatry** [schomery/dictionary#50]
I like your add-on.  It's almost as good as Page Translator Revised, except for one problem.  (actually two, but I'll create a separate issue for it).  It always opens up a new tab when translating, which Page Translator Revised does not do.  Could you add a Settings option to make it so we can re-use the same tab?  Thanks.

**Comment by schomery** [comment]
Thanks for the report. We will have this on the next release.
