### ISSUE TITLE
[Firefox] Blocked by X-Frame-Options Policy

### ISSUE THREAD

**Issue by ozzyjr** [schomery/dictionary#57]
In Firefox Nightly version 72.0a1 a message appears instead of the translation:

Blocked by X-Frame-Options Policy

An error occurred while connecting to translate.google.com.

Nightly prevented this page from loading in this context because the page has an X-Frame-Options policy that disallows it.

![image](https://user-images.githubusercontent.com/12512993/68231566-12826680-ffda-11e9-91db-6bb05c8cb85b.png)

**Comment by vurtomatic** [comment]
Have a bad feeling this can't be resolved: https://www.ghacks.net/2019/11/05/mozilla-bans-all-extensions-that-execute-remote-code/

**Comment by McCoy-thereal** [comment]
See this bug report :

https://bugzilla.mozilla.org/show_bug.cgi?id=1593321

**Comment by schomery** [comment]
The new release is using a standalone popup view which is more stable. So I am closing this bug.
