### ISSUE TITLE
Firefox Extension no longer works

### ISSUE THREAD

**Issue by magusonline** [schomery/dictionary#59]
Whenever I try and use the translator the past few days, it returns just a white box (doesn't even load the translate website).

**Comment by mlopezcoria** [comment]
The same happens to me. I'm using Firefox 82.0.2.

**Comment by tharlab** [comment]
same to me, (idem) :(

**Comment by daichimax** [comment]
The same happens to me. I'm using Firefox 82.0.2.

**Comment by guerini** [comment]
Same problem for me.
I tried with Linux and Windows and I have the same issue.

**Comment by magusonline** [comment]
I'm guessing it won't be fixed for a long time, seeing how active the creator's git is.

**Comment by daichimax** [comment]
WAAAAAAAAAA! IT'S NOT WORKING YET!!!

**Comment by schomery** [comment]
The new release is using a standalone popup view which is more stable. So I am closing this bug.
