### ISSUE TITLE
Word selection bubble is difficult to click

### ISSUE THREAD

**Issue by Thomasc5** [schomery/dictionary#62]
No idea why it is getting so difficult to click on the word selection bubble after the latest update (v. 0.5.1).  The size of the bubble hasn't changed, yet it seems like the "clickable" area of the bubble has shrunken (?)

The browser version is Firefox 82.0.3

**Comment by belaviyo** [comment]
I am not able to reproduce. What is your OS?

**Comment by idma88** [comment]
I have a similar problem. I select the text, try to click on the bubble, but nothing happens. The Ctrl + Click option works and opens a new window with the translator.

Window 7
Firefox 82.0.3 x64

**Comment by Thomasc5** [comment]
> 
> 
> I am not able to reproduce. What is your OS?

Windows 7 Ultimate

**Comment by Thomasc5** [comment]
![Capture](https://user-images.githubusercontent.com/5540385/98939987-3f3e5780-2525-11eb-9558-9ae620defaec.JPG)
