### ISSUE TITLE
Selection bubble often stays on the page, occasionally multiple times

### ISSUE THREAD

**Issue by lopis** [schomery/dictionary#72]
Sometimes the selection bubble stays in the DOM after closing the pop-up. Clicking on it doesn't open a new pop-up nor makes it disappear. Sometimes this happens multiple times on the same page, so more than one bubble can stay stuck floating on a page.

This seems like possible an event handler problem. I was thinking that all bubbles - e.g. all elements matching `.itanywhere-activator` - could be deleted from the page after some time to avoid this. But this would probably only fix the symptom, not the cause of this issue.

**Comment by schomery** [comment]
I have noticed this bug occurring a few times, but I cannot reproduce it now. Could you provide a sample page where the issue occurs? My recent push might have fixed the bug.

**Comment by lopis** [comment]
Ah just got the update. Will observe in the next weeks if it occurs again. It's really hard to reproduce.
