### ISSUE TITLE
Crash, if you selecting too much text

### ISSUE THREAD

**Issue by geokis** [schomery/dictionary#9]
Hello @schomery,
I have a bug for you, if you selecting a lot of text and send an request to translate the selection. The addon seems to crash.

It seems the addon sends permanent request to Google-Translate and it appears an Error message, that Google was not able to handle the request:

![unbenannt](https://cloud.githubusercontent.com/assets/7952956/13975115/6a487afc-f0b2-11e5-892f-cc7d3e06c135.png)

Translation:

> The site with the adress translate.google.com reports:
> We could not handle the translation request.

In this situation Firefox struggles and you must close the tab. Otherwise Firefox is unusable and crashes

**Comment by schomery** [comment]
Well, I don't think there is any solution for this. The translator basically just opens the mobile version of Google Translate. I am not sure how to fix this.

**Comment by geokis** [comment]
I am not sure how the addon works, I'm not a programmer but you could integrate an sign counter.
Before the addon passes the selection to the mobile version, the sign counter checks the amount of signs. 
If the selection is to big, open a new tab with the Google Translate page and send the data to it.

**Comment by schomery** [comment]
This should have already been fixed by now
